### ISSUE TITLE
Seg Faulting and Core Dumps when trying to run on remote server

### ISSUE THREAD

**Issue by LandonSwartz** [Jumpat/SegmentAnythingin3D#8] opened 2023-07-03 18:06 UTC
Hello, I am trying to run SA3D on a remote server using the given examples but every command  causes a seg fault or core dump after installing everything in the repo. 

Example:
    python run_seg_gui.py --config=configs/llff/seg/seg_fern.py --segment --sp_name=_gui --num_prompts=20 --render_opt=train --save_ckpt
Segmentation fault (core dumped)

Is there a remedy for this or is it a limitation of a remote server because of the gui or something else?

**Comment by Jumpat** [comment] 2023-07-04 01:51
Please provide more information about your machine. In our development environment we cannot reproduce this problem. Can you test in which step this problem appears?

**Comment by LandonSwartz** [comment] 2023-07-04 16:31
For both run.py and run_seg_gui.py, the problem occurs at the lib imports. This is lines 15-18 in run.py and lines 14-19 in run_seg_gui.py.

My system's info is:
- CPU: Intel Xeon E5-2630 with 32 cores, 2 threads per core
- GPU: 2 Quadro RTX 8000s and 2 RTX 2080Ti
- OS: AlmaLinux 8.7 (entreprise Ubuntu server)

Thank you, very excited to integrate your work and see how it works with our data!

**Comment by Jumpat** [comment] 2023-07-04 16:53
Please try to import these packages one by one to check which one will lead to the collapse. Currently I think this may be caused by the compiling of the cuda extension.

**Comment by LandonSwartz** [comment] 2023-07-04 17:51
The seg fault does seem to be coming from lines:
`from lib import utils`
`from lib.bbox_utils import *`
`from lib import sam3d`

Another question, in what way should the file structure be set up? The dependencies folder from the installation instructions does not translate to the importing utils files. Let me know if there is something I need to move around there. Thank you!

**Comment by Zanue** [comment] 2023-07-05 02:06
Hi, does the error occur when loading CUDA extension? If so, you can refer to [this issue](https://github.com/sunset1995/DirectVoxGO/issues/13#issuecomment-1074699859) in DVGO. If not, can you provide more information about this error? For example, you can post the full error message.

**Comment by LandonSwartz** [comment] 2023-07-05 20:13
It does seem to be loading the CUDA extension, specifically importing torch_scatter in the dvgo file. What CUDA versions should I be running?

**Comment by Zanue** [comment] 2023-07-06 03:49
There are some relevant issues ([#65](https://github.com/rusty1s/pytorch_scatter/issues/65), [#32](https://github.com/rusty1s/pytorch_scatter/issues/32), [#204](https://github.com/rusty1s/pytorch_scatter/issues/204)) in the repo [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter). It seems that it is worth a try to reinstall it through pip. For our implementation, we use GCC 11.2.0, CUDA=11.3, Python 3.10.6 on Ubuntu 20.04. Hope it will help you.

**Comment by Jumpat** [comment] 2023-07-21 03:27
Closed as finished! Please feel free to ask any other question.

**Closed by Jumpat** 2023-07-21 03:27 UTC
